/**
 * Shared print template for InventoryOS.
 * Provides consistent branding, fonts, and layout across all print outputs.
 */

const BASE_STYLES = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', Arial, sans-serif; font-size: 13px; color: #1e293b; padding: 32px; }
  .doc-header { display: flex; align-items: center; gap: 12px; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #1e293b; }
  .doc-header img { width: 48px; height: 48px; border-radius: 10px; object-fit: cover; }
  .doc-header .brand-name { font-size: 20px; font-weight: 700; color: #0f172a; }
  .doc-header .brand-sub { font-size: 11px; color: #64748b; margin-top: 2px; }
  .doc-title { font-size: 18px; font-weight: 700; color: #0f172a; margin-bottom: 4px; }
  .doc-meta { color: #64748b; font-size: 12px; margin-bottom: 16px; line-height: 1.6; }
  .doc-section { margin-bottom: 16px; }
  .doc-section-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .05em; color: #64748b; margin-bottom: 6px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th { background: #f1f5f9; text-align: left; padding: 8px 10px; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; border-bottom: 2px solid #e2e8f0; color: #475569; }
  td { padding: 8px 10px; border-bottom: 1px solid #f1f5f9; }
  .totals { margin-top: 16px; display: flex; flex-direction: column; align-items: flex-end; gap: 4px; }
  .totals .row { min-width: 260px; display: flex; justify-content: space-between; font-size: 13px; color: #475569; }
  .totals .grand { font-size: 16px; font-weight: 700; color: #0f172a; border-top: 2px solid #1e293b; padding-top: 8px; margin-top: 4px; }
  .badge { display: inline-block; padding: 2px 10px; border-radius: 20px; font-size: 11px; font-weight: 600; text-transform: capitalize; }
  .badge-paid { background: #d1fae5; color: #065f46; }
  .badge-confirmed { background: #e0f2fe; color: #0369a1; }
  .badge-partial { background: #fef3c7; color: #92400e; }
  .badge-draft { background: #f3f4f6; color: #374151; }
  .badge-cancelled { background: #fee2e2; color: #991b1b; }
  .badge-open { background: #fef3c7; color: #92400e; }
  .doc-footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 11px; }
  .doc-footer strong { color: #64748b; }
  @media print { body { padding: 16px; } .no-print { display: none !important; } }
`;

/**
 * Opens a print window with consistent InventoryOS branding.
 * @param {object} opts
 * @param {string} opts.title     - Document title (e.g. "Invoice", "Purchase Order")
 * @param {string} opts.subtitle  - Optional subtitle (e.g. "INV-2024-001")
 * @param {string} opts.companyName - Company name for header
 * @param {string} opts.body      - HTML content for the document body
 * @param {string} [opts.width]   - Window width (default 800)
 * @param {string} [opts.height]  - Window height (default 600)
 */
export function printDocument({ title, subtitle, companyName, body, width = 800, height = 600 }) {
    const w = window.open('', '_blank', `width=${width},height=${height}`);
    w.document.write(`<!DOCTYPE html><html><head><title>${title}</title>
<meta charset="utf-8">
<style>${BASE_STYLES}</style>
</head><body>
  <div class="doc-header">
    <img src="${window.location.origin}/logo.png" alt="Logo" onerror="this.style.display='none'">
    <div>
      <div class="brand-name">${companyName || 'InventoryOS'}</div>
      <div class="brand-sub">Inventory Management Platform</div>
    </div>
  </div>
  <div class="doc-title">${title}</div>
  ${subtitle ? `<div class="doc-meta">${subtitle}</div>` : ''}
  ${body}
  <div class="doc-footer">
    Generated by <strong>InventoryOS</strong> &middot; ${new Date().toLocaleString()}<br>
    www.cramscreative.com
  </div>
  <script>window.onload = () => { setTimeout(() => window.print(), 250); };</script>
</body></html>`);
    w.document.close();
}
